---
AWSTemplateFormatVersion: 2010-09-09
Description: Pululapp User Service.
Parameters:
  PululappEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Pululapp enviroment
  ServiceImageVersion:
    Type: String
    Description: Service image
  ServiceName:
    Type: String
    Description: Service name
    Default: user-svc
  ServiceDescription:
    Type: String
    Description: Service description
    Default: User service
  ServiceRoute:
    Type: String
    Description: Service description
    Default: ANY /user
  ProfileRoute:
    Type: String
    Description: Service description
    Default: ANY /profile
  ECROutput:
    Type: String
    Description: Service ECR cloudformation output
    Default: user-service-ecr-uri
Mappings:
  ServiceConfig:
    staging:
      RAM: 5308
      TimeOut: 60
    prod:
      RAM: 5308
      TimeOut: 60
Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AWSXrayFullAccess
      Policies:
        - PolicyName: !Sub ${ServiceName}-sns-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource:
                  - Fn::ImportValue:
                      !Sub ${PululappEnv}-spot-activity-arn
        - PolicyName: !Sub ${ServiceName}-ssm-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - "*"
        - PolicyName: !Sub ${ServiceName}-dynamodb-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:ConditionCheckItem
                  - dynamodb:GetShardIterator
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:GetRecords
                Resource:
                  - Fn::ImportValue:
                      !Sub ${PululappEnv}-tokens-table-arn
                  - Fn::ImportValue:
                      !Sub ${PululappEnv}-users-table-arn
                  - Fn::Sub:
                    - "${TABLE_ARN}/index/*"
                    - TABLE_ARN: 
                        Fn::ImportValue:
                          !Sub ${PululappEnv}-users-table-arn
        - PolicyName: !Sub ${ServiceName}-sns-notificator-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:ListOriginationNumbers
                  - sns:Publish
                  - sns:ListTopics
                  - sns:ConfirmSubscription
                  - sns:GetSubscriptionAttributes
                  - sns:ListSubscriptions
                  - sns:GetSMSAttributes
                  - sns:OptInPhoneNumber
                  - sns:CheckIfPhoneNumberIsOptedOut
                Resource:
                  - "*"
  ServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures: 
        - arm64
      Code: 
        ImageUri: 
          Fn::Sub:
            - "${ECR_URI}:${VERSION}"
            - VERSION: !Ref ServiceImageVersion
              ECR_URI: 
                Fn::ImportValue:
                  !Ref ECROutput
      Description: !Ref ServiceDescription
      Environment:
        Variables:
          usersTableName:
            Fn::ImportValue:  
              !Sub ${PululappEnv}-users-table-id
          tokensTableName:
            Fn::ImportValue:
              !Sub ${PululappEnv}-tokens-table-id
          userIndexName: 
            Fn::ImportValue:
              !Sub ${PululappEnv}-users-id
      FunctionName: !Sub ${ServiceName}-${PululappEnv}
      MemorySize: !FindInMap ['ServiceConfig', !Ref PululappEnv, 'RAM']
      PackageType: Image
      Role: !GetAtt ServiceRole.Arn
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv
        - Key: Service
          Value: !Ref ServiceName
      Timeout: !FindInMap ['ServiceConfig', !Ref PululappEnv, 'TimeOut']
      TracingConfig:
        Mode: Active

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ServiceLambda
      Principal: apigateway.amazonaws.com
  
  ################################
  #
  # User Service
  #
  ###############################

  ServiceAPIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      Description: !Ref ServiceDescription
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt ServiceLambda.Arn
          - /invocations
      PayloadFormatVersion: '1.0'

  APIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      OperationName: !Sub ${ServiceName}-${PululappEnv}
      RouteKey: !Ref ServiceRoute
      Target: !Join
        - /
        - - integrations
          - !Ref ServiceAPIGatewayIntegration

  APIGatewayIntegrationProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      OperationName: !Sub ${ServiceName}-${PululappEnv}-proxy
      RouteKey: !Sub ${ServiceRoute}/{proxy+}
      Target: !Join
        - /
        - - integrations
          - !Ref ServiceAPIGatewayIntegration
  
  ################################
  #
  # Profile
  #
  ###############################

  ProfileServiceAPIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      Description: !Sub Profile ${ServiceDescription} 
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt ServiceLambda.Arn
          - /invocations
      PayloadFormatVersion: '1.0'
      RequestParameters:
        "overwrite:header.x-internal-user-name": "$context.authorizer.Name"
        "overwrite:header.x-internal-user-id": "$context.authorizer.UserID"
        "overwrite:header.x-internal-user-phone-number": "$context.authorizer.PhoneNumber"

  APIGatewayIntegrationProfile:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      AuthorizationType: CUSTOM
      AuthorizerId:
        Fn::ImportValue: 
          !Sub ${PululappEnv}-auth-default-id
      OperationName: !Sub ${ServiceName}-profile-${PululappEnv}
      RouteKey: !Ref ProfileRoute
      Target: !Join
        - /
        - - integrations
          - !Ref ProfileServiceAPIGatewayIntegration

  APIGatewayIntegrationProfileProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      AuthorizationType: CUSTOM
      AuthorizerId:
        Fn::ImportValue: 
          !Sub ${PululappEnv}-auth-default-id
      OperationName: !Sub ${ServiceName}-profile-${PululappEnv}-proxy
      RouteKey: !Sub ${ProfileRoute}/{proxy+}
      Target: !Join
        - /
        - - integrations
          - !Ref ProfileServiceAPIGatewayIntegration

