name: Deploy {{.ServiceName}} service
on:
  push: # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    branches: 
      - main
    paths:
      - {{.ServicePath}}/** 

jobs:
  {{.ServiceName}}-Service-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build {{.ServiceName}} service to run on lambda
        run: cd ${{ github.workspace }}/{{.ServicePath}} ; sh build.sh ;
      
      - name: Zip code
        run: cd ${{ github.workspace }}/{{.ServicePath}} ; zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy {{.ServiceName}} lambda
        run: aws --version ;  aws lambda update-function-code --function-name {{.ServiceLambdaNale}} --zip-file fileb://${{ github.workspace }}/{{.ServicePath}}/main.zip