---
name: 'Docker build and push'
description: 'Build a docker image, then it publishes it into different images registries'
input:
  docker-tag:
    description: 'Docker tag for the image'
    required: false
    default: ${{ github.sha }}
  docker-image-name:
    description: 'Docker image name.'
    required: true
  docker-context:
    description: "Path to the dockerfile"
    required: true
  
  #####


# outputs:
#   tag:
#     description: 'If tag was not provided, them a tag will be generated and save in the output'
#     value: ${{ steps. }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
      # Setting up repository credentials for pushing immages 
    - name: Logging to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        contex: ${{ inputs.docker-context }} 
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-image-name }}:${{ inputs.docker-tag }}

 
