---
AWSTemplateFormatVersion: 2010-09-09
Description: Pululapp Spot core Service.
Parameters:
  PululappEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Pululapp enviroment
  ServiceImageVersion:
    Type: String
    Description: Service image
  ServiceName:
    Type: String
    Description: Service name
    Default: spot-core-svc
  ServiceDescription:
    Type: String
    Description: Service description
    Default: Spot core operation service
  ServiceRoute:
    Type: String
    Description: Service description
    Default: ANY /spots/core
  ECROutput:
    Type: String
    Description: Service ECR cloudformation output
    Default: spot-creator-ecr-uri
Mappings:
  ServiceConfig:
    staging:
      RAM: 128
      TimeOut: 60
    prod:
      RAM: 128
      TimeOut: 60

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AWSXrayFullAccess
      Policies:
        - PolicyName: !Sub ${ServiceName}-sns-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource:
                  - Fn::ImportValue:
                      !Sub ${PululappEnv}-spot-activity-arn
        - PolicyName: !Sub ${ServiceName}-ssm-${PululappEnv}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - "*"
  ServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures: 
        - arm64
      Code: 
        ImageUri: 
          Fn::Sub:
            - "${ECR_URI}:${VERSION}"
            - VERSION: !Ref ServiceImageVersion
              ECR_URI: 
                Fn::ImportValue:
                  !Ref ECROutput
      Description: !Ref ServiceDescription
      Environment:
        Variables:
          neo4jUser:
            Fn::ImportValue:
              !Sub ${PululappEnv}-neo4j-user
          neo4jPassword:
            Fn::ImportValue:
              !Sub ${PululappEnv}-neo4j-pass
          neo4jUri:
            Fn::ImportValue:
              !Sub ${PululappEnv}-neo4j-uri
          snsArn:
            Fn::ImportValue:
              !Sub ${PululappEnv}-spot-activity-arn
      FunctionName: !Sub ${ServiceName}-${PululappEnv}
      MemorySize: !FindInMap ['ServiceConfig', !Ref PululappEnv, 'RAM']
      PackageType: Image
      Role: !GetAtt ServiceRole.Arn
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv
        - Key: Service
          Value: !Ref ServiceName
      Timeout: !FindInMap ['ServiceConfig', !Ref PululappEnv, 'TimeOut']
      TracingConfig:
        Mode: Active

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ServiceLambda
      Principal: apigateway.amazonaws.com

  ServiceAPIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      Description: !Ref ServiceDescription
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt ServiceLambda.Arn
          - /invocations
      PayloadFormatVersion: '1.0'
      RequestParameters:
        "overwrite:header.x-internal-user-name": "$context.authorizer.Name"
        "overwrite:header.x-internal-user-id": "$context.authorizer.UserID"
        "overwrite:header.x-internal-user-phone-number": "$context.authorizer.PhoneNumber"

  APIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      AuthorizationType: CUSTOM
      AuthorizerId:
        Fn::ImportValue: 
          !Sub ${PululappEnv}-auth-default-id
      OperationName: !Sub ${ServiceName}-${PululappEnv}
      RouteKey: !Ref ServiceRoute
      Target: !Join
        - /
        - - integrations
          - !Ref ServiceAPIGatewayIntegration

  APIGatewayIntegrationProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: 
        Fn::ImportValue: 
            !Sub ${PululappEnv}-central-gateway-id
      AuthorizationType: CUSTOM
      AuthorizerId:
        Fn::ImportValue: 
          !Sub ${PululappEnv}-auth-default-id
      OperationName: !Sub ${ServiceName}-${PululappEnv}-proxy
      RouteKey: !Sub ${ServiceRoute}/{proxy+}
      Target: !Join
        - /
        - - integrations
          - !Ref ServiceAPIGatewayIntegration

