---
AWSTemplateFormatVersion: 2010-09-09
Description: Pululapp services.
Parameters:
  PululappEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Pululapp enviroment
Mappings:
  SubnetConfig:
    staging:
      ReverseProxyDNS: "staging.pululapp.com"
      DomainName: "pululapp.com" 
      DomainHostedZoneId: "Z05194622U3QC4KFX487P"
    prod:
      ReverseProxyDNS: "prod.pululapp.com"
      DomainName: "pululapp.com" 
      DomainHostedZoneId: "Z05194622U3QC4KFX487P"
  TopicsDefaultConfig:
    staging:
      ArchivePolicy: 5
    prod:
      ArchivePolicy: 5

Conditions:
  CreateProdResources: !Equals
    - !Ref PululappEnv
    - prod

Resources:

  ############################################################
  #
  # Central ApiGateway
  #
  ############################################################
 
  CentralGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      # CorsConfiguration: 
      #   Cors
      # CredentialsArn: String
      Description: All backend services are bieng expose by this reverse proxy 
      # DisableExecuteApiEndpoint: Boolean
      Name: !Sub pululapp-central-${PululappEnv}
      ProtocolType: HTTP
      # RouteKey: "$default"
      # RouteSelectionExpression: String
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
      # Target: String
      # Version: String

  DefaultStage:
    DependsOn:
      - CentralGateway
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref CentralGateway
      AutoDeploy: true
      StageName: "$default"

  ApiGatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [SubnetConfig, !Ref PululappEnv, ReverseProxyDNS]
      ValidationMethod: DNS
      CertificateTransparencyLoggingPreference: ENABLED
      SubjectAlternativeNames:
        - !FindInMap [SubnetConfig, !Ref PululappEnv, ReverseProxyDNS]
      DomainValidationOptions:
        - DomainName: !FindInMap [SubnetConfig, !Ref PululappEnv, DomainName]
          HostedZoneId: !FindInMap [SubnetConfig, !Ref PululappEnv, DomainHostedZoneId]

  ApiGatewayCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !FindInMap [SubnetConfig, !Ref PululappEnv, ReverseProxyDNS]
      DomainNameConfigurations: 
        - CertificateArn: !Ref ApiGatewayCertificate
          CertificateName: !FindInMap [SubnetConfig, !Ref PululappEnv, ReverseProxyDNS] 
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
        Stackish: Core

  ApiMapping:
    DependsOn:
      - CentralGateway
      - ApiGatewayCustomDomain
      - DefaultStage 
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref CentralGateway
      Stage: "$default" 
      DomainName: !Ref ApiGatewayCustomDomain

  ApiGatewayRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !FindInMap [SubnetConfig, !Ref PululappEnv, DomainHostedZoneId]
      Name: !FindInMap [SubnetConfig, !Ref PululappEnv, ReverseProxyDNS]
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ApiGatewayCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt ApiGatewayCustomDomain.RegionalDomainName


  ############################################################
  #
  # App Topics
  #
  ############################################################

  SpotActivityTopic:
    Type: AWS::SNS::Topic
    Properties:
      # DeliveryStatusLogging: 
      #   - LoggingConfig
      DisplayName: !Sub "spot-activity-${PululappEnv}"
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv
      TopicName: !Sub "spot-activity-${PululappEnv}"
      # TracingConfig: String

  ############################################################
  #
  # SSM Parameters
  #
  ############################################################

  Neo4jUser:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Username for Neo4j database
      Name: !Sub "neo4j-user-${PululappEnv}"
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
      Tier: Standard
      Type: String
      Value: PLACE_HOLDER
  
  Neo4jPassword:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Password for Neo4j database
      Name: !Sub "neo4j-pass-${PululappEnv}"
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
      Tier: Standard
      Type: String
      Value: PLACE_HOLDER

  Neo4jURI:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: URI for Neo4j database
      Name: !Sub "neo4j-uri-${PululappEnv}"
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
      Tier: Standard
      Type: String
      Value: PLACE_HOLDER
  
  ############################################################
  #
  # DynamoDB tables
  #
  ############################################################

  TokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: TokenId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # ContributorInsightsSpecification: 
      #   Enabled: True
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: TokenId
          KeyType: HASH 
      # BillingMode: PROVISIONED 
      # ProvisionedThroughput: 
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      TableClass: STANDARD 
      TableName: !Sub Tokens-${PululappEnv}
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: PhoneNumber
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # ContributorInsightsSpecification: 
      #   Enabled: True
      DeletionProtectionEnabled: True
      GlobalSecondaryIndexes:
        - ContributorInsightsSpecification: 
            Enabled: True
          IndexName: UserId-index
          KeySchema: 
            - AttributeName: UserId
              KeyType: HASH 
          Projection: 
            ProjectionType: ALL
      KeySchema: 
        - AttributeName: PhoneNumber
          KeyType: HASH 
      TableClass: STANDARD 
      TableName: !Sub Users-${PululappEnv}
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv

  ############################################################
  #
  # ECR Repositories - Prod only in order to have one per both envs
  #
  ############################################################

  AuthRepository:
    Type: AWS::ECR::Repository
    Condition: CreateProdResources
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      RepositoryName: auth-service
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep the latest 5 release images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPatternList": [
                    "*.*.*"
                  ],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep the last 5 untagged images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv

  SpotCoreRepository:
    Type: AWS::ECR::Repository
    Condition: CreateProdResources
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      RepositoryName: spot-core-service
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep the latest 5 release images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPatternList": [
                    "*.*.*"
                  ],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep the last 5 untagged images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv
Outputs:
  ApiGatewayID:
    Value: !Ref CentralGateway
    Export:
      Name: !Sub ${PululappEnv}-central-gateway-id
  TokensTableId:
    Value: !Ref TokensTable
    Export:
      Name: !Sub ${PululappEnv}-tokens-table-id
  TokensTableArn:
    Value: !GetAtt TokensTable.Arn
    Export:
      Name: !Sub ${PululappEnv}-tokens-table-arn
  UsersTableId:
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${PululappEnv}-users-table-id
  UsersIdIndex:
    Value: UserId-index
    Export:
      Name: !Sub ${PululappEnv}-users-id
  UsersTableARN:
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub ${PululappEnv}-users-table-arn
  AuthRepoUri:
    Condition: CreateProdResources
    Value: !GetAtt AuthRepository.RepositoryUri
    Export:
      Name: auth-ecr-uri
  SpotRepoUri:
    Condition: CreateProdResources
    Value: !GetAtt SpotCoreRepository.RepositoryUri
    Export:
      Name: spot-creator-ecr-uri

  ############################################################
  #
  # Topics outputs
  #
  ############################################################

  SpotActivityTopicARN:
    Value: !GetAtt SpotActivityTopic.TopicArn
    Export:
      Name: !Sub ${PululappEnv}-spot-activity-arn
  SpotActivityTopicName:
    Value: !GetAtt SpotActivityTopic.TopicName
    Export:
      Name: !Sub ${PululappEnv}-spot-activity-name
  
  ############################################################
  #
  # SSM outputs
  #
  ############################################################

  Neo4jUserName:
    Value: !Ref Neo4jUser
    Export:
      Name: !Sub ${PululappEnv}-neo4j-user
  Neo4jPasswordName:
    Value: !Ref Neo4jPassword
    Export:
      Name: !Sub ${PululappEnv}-neo4j-pass
  Neo4jURIName:
    Value: !Ref Neo4jURI
    Export:
      Name: !Sub ${PululappEnv}-neo4j-uri
