---
AWSTemplateFormatVersion: 2010-09-09
Description: Pululapp services.
Parameters:
  PululappEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Pululapp enviroment
Mappings:
  SubnetConfig:
    staging:
      ReverseProxyDNS: "staging.pululapp.com"
    prod:
      ReverseProxyDNS: "api.pululapp.com"

Conditions:
  CreateProdResources: !Equals
    - !Ref PululappEnv
    - prod

Resources:
  ############################################################
  #
  # Central ApiGateway
  #
  ############################################################

  CentralGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      # CorsConfiguration: 
      #   Cors
      # CredentialsArn: String
      Description: All backend services are bieng expose by this reverse proxy 
      # DisableExecuteApiEndpoint: Boolean
      Name: !Sub pululapp-central-${PululappEnv}
      ProtocolType: HTTP
      # RouteSelectionExpression: String
      Tags: 
        App: Pululapp
        Env: !Ref PululappEnv
      # Target: String
      # Version: String
  
  ############################################################
  #
  # DynamoDB tables
  #
  ############################################################

  TokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: TokenId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification: 
        Enabled: True
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: TokenId
          KeyType: HASH 
      # BillingMode: PROVISIONED 
      # ProvisionedThroughput: 
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      TableClass: STANDARD 
      TableName: !Sub Tokens-${PululappEnv}
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: PhoneNumber
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification: 
        Enabled: True
      DeletionProtectionEnabled: True
      GlobalSecondaryIndexes:
        - ContributorInsightsSpecification: 
            Enabled: True
          IndexName: UserId-index
          KeySchema: 
            - AttributeName: UserId
              KeyType: HASH 
          Projection: 
            ProjectionType: ALL
      KeySchema: 
        - AttributeName: PhoneNumber
          KeyType: HASH 
      TableClass: STANDARD 
      TableName: !Sub Users-${PululappEnv}
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv

  ############################################################
  #
  # ECR Repositories - Prod only in order to have one per both envs
  #
  ############################################################

  AuthRepository:
    Type: AWS::ECR::Repository
    Condition: CreateProdResources
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      RepositoryName: auth-service
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep the latest 5 release images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPatternList": [
                    "*.*.*"
                  ],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep the last 5 untagged images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags: 
        - Key: App
          Value: Pululapp
        - Key: Env
          Value: !Ref PululappEnv
Outputs:
  ApiGatewayID:
    Value: !Ref CentralGateway
    Export:
      Name: !Sub ${PululappEnv}-central-gateway-id
  TokensTableId:
    Value: !Ref TokensTable
    Export:
      Name: !Sub ${PululappEnv}-tokens-table-id
  TokensTableArn:
    Value: !GetAtt TokensTable.Arn
    Export:
      Name: !Sub ${PululappEnv}-tokens-table-arn
  UsersTableId:
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${PululappEnv}-users-table-id
  UsersIdIndex:
    Value: UserId-index
    Export:
      Name: !Sub ${PululappEnv}-users-id
  UsersTableARN:
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub ${PululappEnv}-users-table-arn
  AuthRepoUri:
    Condition: CreateProdResources
    Value: !GetAtt AuthRepository.RepositoryUri
    Export:
      Name: auth-ecr-uri

