---
name: CI and CD
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

# env:
#   auth-service: { "stack-name": "auth-service", "docker-image-name": "auth-service", "service-dir": "./services/authService" }

jobs:
  service-build-push:
    strategy:
      matrix:
        lookup: [
          {
            "auth-service": { 
              "stack-name": "auth-service",
              "docker-image-name": "auth-service",
              "service-dir": "./services/authService"
            },
            "spots-core-service": { 
              "stack-name": "spots-core-service",
              "docker-image-name": "spot-core-service",
              "service-dir": "./services/spotsCoreService"
            }
          }
        ]
        services: [auth-service, spots-core-service]
    runs-on: ubuntu-latest
    steps:
      - name: echoing
        run: |
          echo ${{ matrix.lookup[matrix.services].stack-name }}
 
    # uses: ./.github/workflows/service-build-deploy.yml
    # secrets: inherit
    # with:
    #   stack-name: ${{ matrix.lookup[matrix.services].stack-name }}
    #   docker-image-name: ${{ matrix.lookup[matrix.services].docker-image-name }}
    #   service-dir: ${{ matrix.lookup[matrix.services].service-dir }}
  

  # service-build-push:
  #   uses: ./.github/workflows/service-build-deploy.yml
  #   secrets: inherit
  #   with:
  #     stack-name: spots-core-service
  #     docker-image-name: spot-core-service 
  #     service-dir: ./services/spotsCoreService
  #
