---
name: CI and CD
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:    
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth-service: ${{ steps.filter.outputs.authService }}
      spots-core-service: ${{ steps.filter.outputs.spotsCoreService }}
      infra-stack: ${{ steps.filter.outputs.infraAWS }}
      confirmation-service: ${{ steps.filter.outputs.confirmationService }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            authService:
              - 'services/authService/**'
            spotsCoreService:
              - 'services/spotsCoreService/**'
            infraAWS:
              - 'infra/aws/template.yml'
            confirmationService:
              - 'services/confirmationService/**'

  infra-stack:
    needs: [changes]
    name:  Main core infra CI/CD
    uses: ./.github/workflows/infra-deploy.yml
    secrets: inherit
    if:  ${{ needs.changes.outputs.infra-stack == 'true' }} 
    with:
      stack-name: pululapp-core
      workdir: ./infra/aws 

  service-build-push:
    needs: [changes]
    strategy:
      matrix:
        lookup: [
          {
            "auth-service": { 
              "stack-name": "auth-service",
              "docker-image-name": "auth-service",
              "service-dir": "./services/authService"
            },
            "spots-core-service": { 
              "stack-name": "spots-core-service",
              "docker-image-name": "spot-core-service",
              "service-dir": "./services/spotsCoreService"
            },
            "confirmation-service": {
              "stack-name": "confirmation-service",
              "docker-image-name": "confirmation-service",
              "service-dir": "./services/confirmationService"
            }
          }
        ]
        services: [auth-service, spots-core-service, confirmation-service]
    name:  ${{ matrix.lookup[matrix.services].stack-name }}
    uses: ./.github/workflows/service-build-deploy.yml
    secrets: inherit
    with:
      deploy: ${{ needs.changes.outputs[matrix.services] == 'true' }}
      stack-name: ${{ matrix.lookup[matrix.services].stack-name }}
      docker-image-name: ${{ matrix.lookup[matrix.services].docker-image-name }}
      service-dir: ${{ matrix.lookup[matrix.services].service-dir }}
  
    # runs-on: ubuntu-latest
    # steps:
    #   - name: echoing
    #     run: |
    #       echo ${{ needs.changes.outputs[matrix.services] }}
    #
