---
name: CI and CD
on:
  push:
    branches:
      - main

jobs:
  build-container:
    uses: ./.github/workflows/container-build-push.yml
    secrets: inherit
    with:
      docker-image-name: spot-core-service 
      docker-context: ./services/spotsCoreService
      docker-tag: ${{ github.sha }}
      docker-build-args: "CMD=lambda"
  #
  # build-container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Docker build and push
  #       uses: ./.github/actions/container_build_push
  #       with:
