---
name: CI and CD
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:    
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth-service: ${{ steps.filter.outputs.authService }}
      spots-core-service: ${{ steps.filter.outputs.spotsCoreService }}
      infra-stack: ${{ steps.filter.outputs.infraAWS }}
      confirmation-service: ${{ steps.filter.outputs.confirmationService }}
      schedule-service: ${{ steps.filter.outputs.scheduleService }}
      schedule-checker-prc: ${{ steps.filter.outputs.scheduleCheckerPrc }}
      online-service: ${{ steps.filter.outputs.onlineService }}
      location-updater-prc: ${{ steps.filter.outputs.locationUpdaterPrc }}
      filter-service: ${{ steps.filter.outputs.filterService }}
      user-service: ${{ steps.filter.outputs.userService }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            authService:
              - 'services/authService/**'
            spotsCoreService:
              - 'services/spotsCoreService/**'
            infraAWS:
              - 'infra/aws/template.yml'
            confirmationService:
              - 'services/confirmationService/**'
            scheduleService :
              - 'services/spotsScheduledService/**'
            scheduleCheckerPrc:
              - 'services/scheduledPatternsChecker/**'
            onlineService :
              - 'services/spotsOnlineService/**'
            locationUpdaterPrc:
              - 'services/locationDataUpdater/**'
            filterService :
              - 'services/filter/**'
            userService :
              - 'services/userService/**'

  infra-stack:
    needs: [changes]
    name:  Main core infra CI/CD
    uses: ./.github/workflows/infra-deploy.yml
    secrets: inherit
    if:  ${{ needs.changes.outputs.infra-stack == 'true' }} 
    with:
      stack-name: pululapp-core
      workdir: ./infra/aws 

  service-build-push:
    needs: [changes]
    strategy:
      matrix:
        lookup: [
          {
            "auth-service": { 
              "stack-name": "auth-service",
              "docker-image-name": "auth-service",
              "service-dir": "./services/authService"
            },
            "spots-core-service": { 
              "stack-name": "spots-core-service",
              "docker-image-name": "spot-core-service",
              "service-dir": "./services/spotsCoreService"
            },
            "confirmation-service": {
              "stack-name": "confirmation-service",
              "docker-image-name": "confirmation-service",
              "service-dir": "./services/confirmationService"
            },
            "schedule-service": {
              "stack-name": "spots-schedule-service",
              "docker-image-name": "spot-schedule-service",
              "service-dir": "./services/spotsScheduledService"
            },
            "schedule-checker-prc": {
              "stack-name": "schedule-checker-prc",
              "docker-image-name": "schedule-checker-process",
              "service-dir": "./services/scheduledPatternsChecker"
            },
            "online-service": {
              "stack-name": "spot-online-service",
              "docker-image-name": "spot-online-service",
              "service-dir": "./services/spotsOnlineService"
            },
            "location-updater-prc": {
              "stack-name": "location-updater-process",
              "docker-image-name": "location-updater-process",
              "service-dir": "./services/locationDataUpdater"
            },
            "filter-service": {
              "stack-name": "filter-service",
              "docker-image-name": "filter-service",
              "service-dir": "./services/filter"
            },
            "user-service": {
              "stack-name": "user-service",
              "docker-image-name": "user-service",
              "service-dir": "./services/userService"
            },
          }
        ]
        services: [auth-service, spots-core-service, confirmation-service, schedule-service, schedule-checker-prc, online-service, location-updater-prc, filter-service, user-service]
    name:  ${{ matrix.lookup[matrix.services].stack-name }}
    uses: ./.github/workflows/service-build-deploy.yml
    secrets: inherit
    with:
      deploy: ${{ needs.changes.outputs[matrix.services] == 'true' }}
      stack-name: ${{ matrix.lookup[matrix.services].stack-name }}
      docker-image-name: ${{ matrix.lookup[matrix.services].docker-image-name }}
      service-dir: ${{ matrix.lookup[matrix.services].service-dir }}
  
