---
name: CI and CD
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

# env:
#   auth-service: { "stack-name": "auth-service", "docker-image-name": "auth-service", "service-dir": "./services/authService" }

jobs:    
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth-service: ${{ steps.filter.outputs.authService }}
      spots-core-service: ${{ steps.filter.outputs.spotsCoreService }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            authService:
              - 'services/authService/**'
            spotsCoreService:
              - 'services/spotsCoreService/**'

  service-build-push:
    needs: [changes]
    strategy:
      matrix:
        lookup: [
          {
            "auth-service": { 
              "stack-name": "auth-service",
              "docker-image-name": "auth-service",
              "service-dir": "./services/authService"
            },
            "spots-core-service": { 
              "stack-name": "spots-core-service",
              "docker-image-name": "spot-core-service",
              "service-dir": "./services/spotsCoreService"
            }
          }
        ]
        services: [auth-service, spots-core-service]
    name:  ${{ matrix.lookup[matrix.services].stack-name }}
    # if: ${{ needs.changes.outputs.matrix.services == 'true' }} 
    # uses: ./.github/workflows/service-build-deploy.yml
    # secrets: inherit
    # with:
    #   stack-name: ${{ matrix.lookup[matrix.services].stack-name }}
    #   docker-image-name: ${{ matrix.lookup[matrix.services].docker-image-name }}
    #   service-dir: ${{ matrix.lookup[matrix.services].service-dir }}



    runs-on: ubuntu-latest
    steps:
      - name: echoing
        run: |
          echo ${{ needs.changes.outputs[matrix.services] }}

