---
name: CI and CD
on:
  push:
    branches:
      - main

jobs:
  build-container:
    uses: ./.github/workflows/container-build-push.yml
    secrets: inherit
    with:
      docker-image-name: spot-core-service 
      docker-context: ./services/spotsCoreService
      docker-tag: ${{ github.sha }}
      docker-build-args: "CMD=lambda"
  
  deploy-cloudformation:
    uses: ./.github/workflows/cloudformation-deploy.yml
    secrets: inherit
    needs: [build-container]
    with:
      stack-name: spots-core-service
      work-dir: ./services/spotsCoreService 
      service-docker-tag: ${{ github.sha }}
      pululapp-env: staging
