---
name: CI and CD
on:
  push:
    branches:
      - main

jobs:
  service-build-push:
    uses: ./.github/workflows/service-build-deploy.yml
    secrets: inherit
    with:
      stack-name: spots-core-service
      docker-image-name: spot-core-service 
      service-dir: ./services/spotsCoreService

