---
name: 'Cloudformation deploy'

on:
  workflow_call:
    inputs:
      stack-name:
        description: "The name of the CloudFormation stack"
        required: true
        type: string
      workdir:
        description: "The path to the CloudFormation template"
        required: true
        type: string
      parameter-overrides:
        description: 'Parameters for cloudformartion, comma delimited'
        required: false
        type: string
      pululapp-env:
        description: 'Pululapp Env'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true

defaults:
  run:
    shell: bash

jobs:
  Cloudformation-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.pululapp-env }}
    steps:
     
      #######################################################
      #
      # Basic configuration 
      #
      # #####################################################
      
      - name: Checkout
        uses: actions/checkout@v4
      
      #######################################################
      #
      # AWS Setup 
      #
      # #####################################################
      
      # AWS ECR Repository
      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #######################################################
      #
      # Publish Service 
      #
      # #####################################################

      - name: Generate parameter-overrides
        run: |
          # newParams:='PululappEnv=${{ inputs.pululapp-env }}'
          if [ -z "${{ inputs.parameter-overrides }}" ]
          then
                echo "${{ inputs.parameter-overrides }}  is empty"
                echo "PARAMS_OVERVIEW='PululappEnv=${{ inputs.pululapp-env }}'"  >> "${GITHUB_ENV}"
          else
            # newParams:='PululappEnv=${{ inputs.pululapp-env }}, ${{ inputs.parameter-overrides }}'
            echo "PARAMS_OVERVIEW='PululappEnv=${{ inputs.pululapp-env }},${{ inputs.parameter-overrides }}'" >> "${GITHUB_ENV}"
          fi

          # echo "The resulting params are $newParams" 

      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ inputs.stack-name }}-${{ inputs.pululapp-env }}
          template: ${{ inputs.workdir }}/template.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM, CAPABILITY_IAM
          parameter-overrides: ${{ env.PARAMS_OVERVIEW }} 

