name: Deploy spotsScheduledService service
on:
  push: # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    branches: 
      - main
    paths:
      - services/spotsScheduledService/** 

jobs:
  spotsScheduledService-Service-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          go-version-file: ${{ github.workspace }}/services/spotsScheduledService/go.mod

      - name: Build spotsScheduledService service to run on lambda
        run: | 
          # export GOMOD="${{ github.workspace }}/services/spotsScheduledService/go.mod"
          cd ${{ github.workspace }}/services/spotsScheduledService ; sh build.sh ;
      
      - name: Zip code
        run: cd ${{ github.workspace }}/services/spotsScheduledService ; zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy spotsScheduledService lambda
        run: aws --version ;  aws lambda update-function-code --function-name SpotsScheduledService --zip-file fileb://${{ github.workspace }}/services/spotsScheduledService/main.zip