name: Deploy Go services
on:
  push: # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
    branches:  # This is a filter that belongs to push
      - main
    paths:
      - '/infra/services/**'

jobs:
  Money-Saver-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build rdsMoneySaver service to run on lambda
        run: cd ${{ github.workspace }}/infra/services/rdsMoneySaver ; sh build.sh ;
      
      - name: Zip code
        run: cd ${{ github.workspace }}/infra/services/rdsMoneySaver ; zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to rdsMoneySaver lambda
        run: aws --version ;  aws lambda update-function-code --function-name RdsMoneySaver --zip-file fileb://${{ github.workspace }}/infra/services/rdsMoneySaver/main.zip
  AWS-Services-Change-Notifer-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build awsServiceChangesNotifier service to run on lambda
        run: cd ${{ github.workspace }}/infra/services/awsServiceChangesNotifier ; sh build.sh ;
      
      - name: Zip code
        run: cd ${{ github.workspace }}/infra/services/awsServiceChangesNotifier ; zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to awsServiceChangesNotifier lambda
        run: aws --version ;  aws lambda update-function-code --function-name AWSServiceChangesNotifier --zip-file fileb://${{ github.workspace }}/infra/services/awsServiceChangesNotifier/main.zip
  Email-Sender-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build emailSender service to run on lambda
        run: cd ${{ github.workspace }}/infra/services/emailSender ; sh build.sh ;
      
      - name: Zip code
        run: cd ${{ github.workspace }}/infra/services/emailSender; zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to awsServiceChangesNotifier lambda
        run: aws --version ;  aws lambda update-function-code --function-name EmailSende --zip-file fileb://${{ github.workspace }}/infra/services/emailSender/main.zip

